name: bc-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - chainlit
    - langgraph
    - langchain
    - langchain-google-genai
    - langchain-mcp-adapters

# specify versions later (conda export)